server:
  port: 8091

spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

zuul:
  routes:
    client1:
      path: /client1/**
      serviceId: client1
      sensitiveHeaders: "*"
    pillar:
      path: /pillar/**
      serviceId: pillar
      sensitiveHeaders: "*"
    auth:
      path: /uaa/**
      serviceId: oauth-center
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/uaa/oauth/token
      user-authorization-uri: http://localhost:${server.port}/uaa/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/uaa/user
      prefer-token-info: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

